pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            // RetroFuturaGradle
            name 'GTNH Maven'
            url 'https://nexus.gtnewhorizons.com/repository/public/'
            mavenContent {
                includeGroup 'com.gtnewhorizons'
                includeGroup 'com.gtnewhorizons.retrofuturagradle'
            }
        }
        maven {
            name = 'clojars'
            url = 'https://repo.clojars.org'
        }
        mavenCentral()
        mavenLocal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}

rootProject.name = 'clojure-academy'

// Include all subprojects
include ':forge_1_12_2'
include ':forge_1_15_2'
include ':forge_1_16_5'
include ':mcmod'
include ':acmod'

// Set the project directory for each subproject
project(':forge_1_12_2').projectDir = file('forge_1_12_2')
project(':forge_1_15_2').projectDir = file('forge_1_15_2')
project(':forge_1_16_5').projectDir = file('forge_1_16_5')
project(':mcmod').projectDir = file('mcmod')  // Fixed: point to mcmod folder, not common
project(':acmod').projectDir = file('acmod')
