apply plugin: 'java'
apply plugin: 'dev.clojurephant.clojure'
apply plugin: 'maven-publish'

archivesBaseName = "${modid}-common"

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

checkClojure.enabled = false

repositories {
    mavenCentral()
    maven {
        name = 'ClojarsRepo'
        url = 'https://repo.clojars.org'
    }
    maven { url = 'https://plugins.gradle.org/m2' }
}

dependencies {
    implementation project(':common')
    implementation 'org.clojure:clojure:1.10.1'
    implementation 'org.clojure:tools.logging:1.2.4'
    implementation 'org.clojure:data.json:2.4.0'
    testImplementation 'org.clojure:test.check:1.1.1'
    testImplementation 'org.mockito:mockito-core:3.12.4'
}

sourceSets {
    main {
        java.srcDirs = ['src/main/java']
        clojure.srcDirs = ['src/main/clojure']
        resources.srcDirs = ['src/main/resources']
    }
    test {
        clojure {
            srcDirs = ['src/test/clojure']
        }
        resources {
            srcDirs = ['src/test/resources']
        }
    }
}

clojure {
    builds.main.reflection = 'warn'
    builds.main.aotAll()
    builds.main.compiler.directLinking = true
    builds {
        test {
            reflection = 'warn'
            aotNamespaces = ['cn.academy.core.test.*']
        }
    }
}

jar {
    from sourceSets.main.output
    manifest {
        attributes([
            'Implementation-Title': 'Clojure Academy',
            'Implementation-Version': '1.0',
            'Implementation-Vendor' : 'academy',
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

task createDirectoryStructure {
    doLast {
        mkdir "src/main/java"
        mkdir "src/main/clojure"
        mkdir "src/main/resources"
    }
}

build.dependsOn createDirectoryStructure

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat "full"
    }
}
