buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'dev.clojurephant.clojure'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'

version = "1.0"
group = "cn.academy"
archivesBaseName = "clojure-academy-1.12.2"

sourceCompatibility = targetCompatibility = '1.8'
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    version = "1.12.2-14.23.5.2855"
    runDir = "run"
    mappings = "snapshot_20171003"
    
    makeObfSourceJar = false
}

checkClojure.enabled = false

dependencies {
    implementation project(':acmod')
    implementation project(':common')
}

sourceSets {
    main {
        java { srcDirs = ['src/main/java'] }
        clojure { srcDirs = ['src/main/clojure'] }
        resources { srcDirs = ['src/main/resources'] }
    }
}

clojure {
    builds.main.reflection = 'warn'
    builds.main.aotAll()
    builds.main.compiler.directLinking = true
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
        
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    from sourceSets.main.output
    manifest {
        attributes([
            "Specification-Title": "ClojureAcademy",
            "Specification-Vendor": "clojure-academy",
            "Specification-Version": "1",
            "Implementation-Title": "ClojureAcademy",
            "Implementation-Version": project.version,
            "Implementation-Vendor" :"clojure-academy",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

task createDirectoryStructure {
    doLast {
        mkdir "src/main/java"
        mkdir "src/main/clojure"
        mkdir "src/main/resources"
        mkdir "src/main/resources/assets/${mod_name}"
        mkdir "run"
    }
}

build.dependsOn createDirectoryStructure