# Mod Information
mod_version=1.0.0
mod_id=academy_craft
mod_name=Academy Craft
root_package=cn.academy.forge
mod_description=A Minecraft mod based on Academy City, where science prevails with ESPers.
mod_authors=Lambda Innovation, Academy Craft Team
mod_credits=Lambda Innovation, Academy Craft Team
mod_url=https://github.com/LambdaInnovation/AcademyCraft
mod_update_json=
mod_logo_path=academycraft.png

# Mixins
use_mixins=false
mixin_booter_version=8.0
mixin_refmap=
mixin_package=cn.academy.forge.mixin
mixin_configs=
generate_mixins_json=false

# Tags
use_tags=false
tag_class_name=cn.academy.forge.Tags

# Access Transformer
use_access_transformer=false
access_transformer_locations=

# CoreMod
is_coremod=false
coremod_includes_mod=false
coremod_plugin_class_name=

# AssetMover
use_asset_mover=false
asset_mover_version=2.5

# Other properties
show_testing_output=false
enable_junit_testing=false
publish_with_changelog=false
change_minecraft_sources=false
generate_sources_jar=true
generate_javadocs_jar=true
use_modern_java_syntax=false
use_dependency_at_files=true
minecraft_username=Developer
mapping_channel=stable
mapping_version=39
