modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="academy"
version="${version}"
displayName="Clojure Academy"
authors="Academy Team"
description='''
Academy Craft reimplemented in Clojure
'''

[[dependencies.academy]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.academy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"