modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="cljacademy"
version="1.0.0"
displayName="ClojureAcademy"
description='''
A Minecraft mod written in Clojure demonstrating modular architecture
'''

[[dependencies.cljacademy]]
modId="forge"
mandatory=true
versionRange="[36.2.39,)"
ordering="NONE"
side="BOTH"

[[dependencies.cljacademy]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"