plugins {
    id 'clojure'
    id 'java-library'
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.clojars.org/' }
}

dependencies {
    implementation 'org.clojure:clojure:1.11.1'
    implementation 'org.clojure:tools.logging:1.2.4'
    testImplementation 'org.clojure:test.check:1.1.1'
}

sourceSets {
    main {
        clojure {
            srcDirs = ['src/main/clojure']
        }
        resources {
            srcDirs = ['src/main/resources']
        }
    }
    test {
        clojure {
            srcDirs = ['src/test/clojure']
        }
    }
}

jar {
    manifest {
        attributes(
            'Implementation-Title': project.name,
            'Implementation-Version': project.version
        )
    }
}