buildscript {
    repositories {
        maven { url = 'https://files.minecraftforge.net/maven' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '3.+', changing: true
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'clojure'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'

version = '1.0'
group = 'cn.academy'
archivesBaseName = 'forge_1_16_5'

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

minecraft {
    mappings channel: 'snapshot', version: '20210309-1.16.5'
    
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                forge_1_16_5 {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                forge_1_16_5 {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = 'https://repo.clojars.org/' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.16.5-36.2.39'
    
    implementation 'org.clojure:clojure:1.11.1'
    implementation 'org.clojure:tools.logging:1.2.4'
    implementation project(':mcmod')  // Add dependency on mcmod project
    
    testImplementation 'org.clojure:test.check:1.1.1'
}

sourceSets {
    main {
        clojure {
            srcDirs = ['src/main/clojure']
        }
        resources {
            srcDirs = ['src/main/resources']
        }
    }
    test {
        clojure {
            srcDirs = ['src/test/clojure']
        }
    }
}

jar {
    manifest {
        attributes([
            "Specification-Title": "forge_1_16_5",
            "Specification-Vendor": "academy",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"academy",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}